### ISSUE TITLE
搜狗浏览器报错

### ISSUE THREAD

**Issue by sankun33** [webLiang/Pornhub-Video-Downloader-Plugin-v3#10]
Permission 'sidePanel' is unknown or URL pattern is malformed.
每次下载了一点点就不动了，要不就是正在连接。

**Comment by webLiang** [comment]
todo

**Comment by webLiang** [comment]
可以试试 https://github.com/webLiang/Pornhub-Video-Downloader-Plugin-v3/releases/tag/v1.0.13  去除了sidePanel 权限
