### ISSUE TITLE
报错Unauthorized 

### ISSUE THREAD

**Issue by QihangYang** [webLiang/Pornhub-Video-Downloader-Plugin-v3#2]
Unauthorized
We're sorry, the request requires user authentication

**Comment by webLiang** [comment]
Which website is this?

**Comment by webLiang** [comment]
The details page of the video website is supported, and an error may be reported on the homepage,Repair after the logic of the error logic of the homepage

**Comment by QihangYang** [comment]
抱歉，是我的梯子的问题。梯子ip被污染了导致被pornhub拦截了，换了一个梯子可以正常使用了。我的问题解决了，非常感谢大佬的贡献！
