### ISSUE TITLE
建议xvideos加入1080P的下载选项

### ISSUE THREAD

**Issue by Tsubamei** [webLiang/Pornhub-Video-Downloader-Plugin-v3#3]
目前xvideo只有low和high两个选项，分别对应240p和360p，选择1080p画质播放也是如此，希望能加入更多分辨率选项

**Comment by webLiang** [comment]
1080p对应m3u8链接  需要解析m3u8 后续支持下

**Comment by webLiang** [comment]
> 目前xvideo只有low和high两个选项，分别对应240p和360p，选择1080p画质播放也是如此，希望能加入更多分辨率选项

https://github.com/webLiang/Pornhub-Video-Downloader-Plugin-v3/releases 已经支持

**Comment by Tsubamei** [comment]
> > 目前xvideo只有low和high两个选项，分别对应240p和360p，选择1080p画质播放也是如此，希望能加入更多分辨率选项
> 
> https://github.com/webLiang/Pornhub-Video-Downloader-Plugin-v3/releases 已经支持

经过测试可以了，下载速度非常快！
