### ISSUE TITLE
能不能做个crx格式的，某些安卓装不了zip

### ISSUE THREAD

**Issue by yongdaimei** [webLiang/Pornhub-Video-Downloader-Plugin-v3#4]

**Comment by webLiang** [comment]
安卓可以试试这个浏览器 自带了
https://www.quetta.net/zh/

**Comment by webLiang** [comment]
链接有crx的可以试试

https://github.com/webLiang/Pornhub-Video-Downloader-Plugin-v3/releases/tag/v1.0.4
