### ISSUE TITLE
建议：定制下载文件名格式

### ISSUE THREAD

**Issue by opkhkh** [webLiang/Pornhub-Video-Downloader-Plugin-v3#6]
今天安装插件用了一下，很好用。
建议下载文件名格式自动保存为：演员名+上传日期+视频标题。
目前下载文件名只有视频标题，如果标题包含空格，空格也会被删除，建议保留空格，或者用点号“·”代替空格。
以上只是建议。

**Comment by webLiang** [comment]
todo

**Comment by webLiang** [comment]
1.0.11 增加支持 文件名增加空格  演员名
上传日期暂时不加

**Comment by webLiang** [comment]
> > 1.0.11 增加支持 文件名增加空格 演员名 上传日期暂时不加
> 
> 貌似文件名仍然没有添加演员名，文件名以两个短横线开头 使用的是chrome浏览器

可能是只适配了移动端看看pc版本

**Comment by webLiang** [comment]
https://github.com/webLiang/Pornhub-Video-Downloader-Plugin-v3/releases/tag/v1.0.12
试试

**Comment by mabenhao** [comment]
> 1.0.11 增加支持 文件名增加空格 演员名 上传日期暂时不加

emm，后面都不考虑增加上传时间吗
